### ISSUE TITLE
Multiple validation

### ISSUE THREAD

**Issue by muhammetsahin** [winstongubantes/matcha.validation#1]
Hi,

First of all, You did really good job.congratulations.

I've a question about multiple validation.

For example, how can i handle email property "isnotempty" and "email" rule at the same time?

Thanks.

**Comment by winstongubantes** [comment]
You can create your own custom validation by inheriting ValidationRule<T> which validate isnotempty and email, please refer to this link => https://github.com/winstongubantes/MatchaValidation#validationrule
